site_name: PKT Documentation
nav:
    - Home: index.md
    - PKT Electrum: electrum/index.md
    - Mining: mining/index.md
    - Pool Operation: mining/pool_setup_guide.md
    - Pktd: pktd/index.md
    - PKTWallet: pktd/pktwallet.md
    - Electrum Import: pktd/migrating_from_electrum.md
