site_name: PKT Documentation
nav:
    - Home: index.md
    - Electrum Wallet: electrum/index.md
    - Mining: mining/index.md
    - Pktd: pktd/index.md
    - PKTWallet: pktd/pktwallet.md
    - PKTWallet Electrum Import: pktd/migrating_from_electrum.md